- name: copy files to destination
  hosts: all
  become: yes
  tasks:
    - name: copy src.txt as dest.txt in the same dir
      copy:
        src: /var/lib/jenkins/workspace/mahalogin/target/mahaLogin-2.0.war
        dest: /opt/tomcat/webapps
