- name: copy files to destination
  hosts: all
  become: yes
  tasks:
    - name: copy src.txt as dest.txt in the same dir
      copy:
        src: /opt/artifact/target/mahaLogin-2.0.war
        dest: /opt/tomcat/webapps
       notify: Restart tomcat
  handlers:
    - name: Restart tomcat
      service: 
         name: "tomcat"
         state: restarted
